baseURL = 'https://johncosta.tech/'
languageCode = 'en-uk'
title = 'John Costa'
theme = 'risotto'
[params]
  palette = 'tokyo-night-dark'

[menu]
[[menu.main]]
    name = 'Blog'
    pageRef = '/blog'
[[menu.main]]
    name = 'Projects'
    pageRef = '/projects'

[params.about]
title = "John Costa"
description = "Software Engineer"

[params.theme]
palette = "tokyo-night-dark"

# Sidebar: social links
# Available icon sets:
# * FontAwesome 6 <https://fontawesome.com/> ('fa-brands', 'fa-normal', or 'fa-solid' for brands)
# * Academicons <https://jpswalsh.github.io/academicons> ('ai ai-')

[Author]
    name = "John Costa"
    email  = "johncosta027@gmail.com"

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/JohnCosta27/JohnTech"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:johncosta027@gmail.com"
[[params.socialLinks]]
icon = "fa-brands fa-linkedin"
title = "LinkedIn"
url = "https://www.linkedin.com/in/john-costa-b883971b5/"

[taxonomies]
tags = "tags"
