baseURL = 'https://example.org/'
languageCode = 'en-uk'
title = 'John Costa'
theme = 'risotto'

[menu]
[[menu.main]]
    name = 'Blog'
    pageRef = '/blog'
[[menu.main]]
    name = 'Projects'
    pageRef = '/projects'

[params.about]
title = "John Costa"
description = "Software Engineer"

# Sidebar: social links
# Available icon sets:
# * FontAwesome 6 <https://fontawesome.com/> ('fa-brands', 'fa-normal', or 'fa-solid' for brands)
# * Academicons <https://jpswalsh.github.io/academicons> ('ai ai-')

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/JohnCosta27/JohnTech"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:example@example.com"

[taxonomies]
tags = "tags"
